export interface HiringJob {
  id: string;
  country: string;
  code: string;
  city: string;
  company: string;
  title: string;
  industry: string;
  experience: string;
  salary: string;
  education: string;
  english: string;
  benefits: string;
  matchScore?: number;
}

export const HIRING_JOBS_CATALOG: HiringJob[] = [
  {
    id: "JOB-001",
    country: "Qatar",
    code: "qa",
    city: "Doha",
    company: "Qatar Airways Catering",
    title: "Chef de Partie",
    industry: "Hospitality",
    experience: "5+ yrs",
    salary: "QAR 5,500",
    education: "Diploma",
    english: "Intermediate",
    benefits: "Accommodation, Transport, Meals",
    matchScore: 98,
  },
  {
    id: "JOB-002",
    country: "Qatar",
    code: "qa",
    city: "Doha",
    company: "Marriott Doha",
    title: "Senior Chef de Partie",
    industry: "Hotel",
    experience: "8+ yrs",
    salary: "QAR 6,800",
    education: "Diploma",
    english: "Good",
    benefits: "Accommodation, Medical",
    matchScore: 96,
  },
  {
    id: "JOB-003",
    country: "Qatar",
    code: "qa",
    city: "Doha",
    company: "Mandarin Oriental",
    title: "Demi Chef de Partie",
    industry: "Luxury Hotel",
    experience: "3+ yrs",
    salary: "QAR 4,800",
    education: "Diploma",
    english: "Good",
    benefits: "Accommodation",
    matchScore: 94,
  },
  {
    id: "JOB-004",
    country: "Saudi Arabia",
    code: "sa",
    city: "Riyadh",
    company: "Four Seasons",
    title: "Chef de Partie",
    industry: "Hospitality",
    experience: "5+ yrs",
    salary: "SAR 6,000",
    education: "Diploma",
    english: "Good",
    benefits: "Accommodation",
    matchScore: 95,
  },
  {
    id: "JOB-005",
    country: "Saudi Arabia",
    code: "sa",
    city: "Jeddah",
    company: "Radisson Blu",
    title: "Hot Kitchen Chef",
    industry: "Hotel",
    experience: "4+ yrs",
    salary: "SAR 5,400",
    education: "Diploma",
    english: "Intermediate",
    benefits: "Medical",
    matchScore: 93,
  },
  {
    id: "JOB-006",
    country: "Saudi Arabia",
    code: "sa",
    city: "Riyadh",
    company: "Catrion Group",
    title: "Catering Chef",
    industry: "Catering",
    experience: "6+ yrs",
    salary: "SAR 6,500",
    education: "Diploma",
    english: "Intermediate",
    benefits: "Food + Housing",
    matchScore: 92,
  },
  {
    id: "JOB-007",
    country: "UAE",
    code: "ae",
    city: "Dubai",
    company: "Atlantis The Palm",
    title: "Chef de Partie",
    industry: "Luxury Resort",
    experience: "5+ yrs",
    salary: "AED 5,800",
    education: "Diploma",
    english: "Good",
    benefits: "Housing",
    matchScore: 97,
  },
  {
    id: "JOB-008",
    country: "UAE",
    code: "ae",
    city: "Abu Dhabi",
    company: "Emirates Palace",
    title: "Senior Chef",
    industry: "Luxury Hotel",
    experience: "8+ yrs",
    salary: "AED 8,000",
    education: "Diploma",
    english: "Fluent",
    benefits: "Medical",
    matchScore: 99,
  },
  {
    id: "JOB-009",
    country: "UAE",
    code: "ae",
    city: "Dubai",
    company: "Hilton Dubai",
    title: "Cold Kitchen Chef",
    industry: "Hotel",
    experience: "4+ yrs",
    salary: "AED 5,300",
    education: "Diploma",
    english: "Good",
    benefits: "Accommodation",
    matchScore: 91,
  },
  {
    id: "JOB-010",
    country: "Kuwait",
    code: "kw",
    city: "Kuwait City",
    company: "Hilton Kuwait",
    title: "Chef de Partie",
    industry: "Hospitality",
    experience: "5+ yrs",
    salary: "KWD 500",
    education: "Diploma",
    english: "Good",
    benefits: "Accommodation",
    matchScore: 94,
  },
  {
    id: "JOB-011",
    country: "Oman",
    code: "om",
    city: "Muscat",
    company: "Kempinski Muscat",
    title: "Chef de Partie",
    industry: "Resort",
    experience: "4+ yrs",
    salary: "OMR 650",
    education: "Diploma",
    english: "Intermediate",
    benefits: "Housing",
    matchScore: 90,
  },
  {
    id: "JOB-012",
    country: "Bahrain",
    code: "bh",
    city: "Manama",
    company: "Gulf Hotel",
    title: "Continental Chef",
    industry: "Hotel",
    experience: "5+ yrs",
    salary: "BHD 700",
    education: "Diploma",
    english: "Good",
    benefits: "Accommodation",
    matchScore: 92,
  },
  {
    id: "JOB-013",
    country: "Qatar",
    code: "qa",
    city: "Doha",
    company: "Ezdan Palace",
    title: "Sous Chef",
    industry: "Luxury Hotel",
    experience: "8+ yrs",
    salary: "QAR 7,500",
    education: "Diploma",
    english: "Fluent",
    benefits: "Housing",
    matchScore: 96,
  },
  {
    id: "JOB-014",
    country: "Saudi Arabia",
    code: "sa",
    city: "Riyadh",
    company: "Marriott",
    title: "Chef de Partie",
    industry: "Hotel",
    experience: "5+ yrs",
    salary: "SAR 5,800",
    education: "Diploma",
    english: "Good",
    benefits: "Medical",
    matchScore: 93,
  },
  {
    id: "JOB-015",
    country: "UAE",
    code: "ae",
    city: "Dubai",
    company: "Rotana Hotels",
    title: "Demi Chef",
    industry: "Hotel",
    experience: "3+ yrs",
    salary: "AED 4,700",
    education: "Diploma",
    english: "Good",
    benefits: "Housing",
    matchScore: 89,
  },
  {
    id: "JOB-016",
    country: "Qatar",
    code: "qa",
    city: "Doha",
    company: "Crowne Plaza",
    title: "Pastry Chef",
    industry: "Hotel",
    experience: "5+ yrs",
    salary: "QAR 5,300",
    education: "Diploma",
    english: "Good",
    benefits: "Accommodation",
    matchScore: 94,
  },
  {
    id: "JOB-017",
    country: "Saudi Arabia",
    code: "sa",
    city: "Makkah",
    company: "Rotana",
    title: "Pastry Chef",
    industry: "Hotel",
    experience: "5+ yrs",
    salary: "SAR 5,500",
    education: "Diploma",
    english: "Intermediate",
    benefits: "Meals",
    matchScore: 91,
  },
  {
    id: "JOB-018",
    country: "UAE",
    code: "ae",
    city: "Sharjah",
    company: "Sheraton",
    title: "Bakery Chef",
    industry: "Hotel",
    experience: "4+ yrs",
    salary: "AED 4,900",
    education: "Diploma",
    english: "Good",
    benefits: "Housing",
    matchScore: 90,
  },
  {
    id: "JOB-019",
    country: "Qatar",
    code: "qa",
    city: "Doha",
    company: "Hyatt Regency",
    title: "Restaurant Supervisor",
    industry: "Hospitality",
    experience: "4+ yrs",
    salary: "QAR 5,000",
    education: "Bachelor",
    english: "Good",
    benefits: "Accommodation",
    matchScore: 95,
  },
  {
    id: "JOB-020",
    country: "Saudi Arabia",
    code: "sa",
    city: "Jeddah",
    company: "Hilton",
    title: "Kitchen Supervisor",
    industry: "Hotel",
    experience: "6+ yrs",
    salary: "SAR 6,200",
    education: "Diploma",
    english: "Good",
    benefits: "Housing",
    matchScore: 93,
  },
  {
    id: "JOB-021",
    country: "Qatar",
    code: "qa",
    city: "Doha",
    company: "Hamad Medical Corp",
    title: "Hospital Cook",
    industry: "Healthcare",
    experience: "3+ yrs",
    salary: "QAR 4,500",
    education: "Diploma",
    english: "Basic",
    benefits: "Accommodation",
    matchScore: 88,
  },
  {
    id: "JOB-022",
    country: "UAE",
    code: "ae",
    city: "Dubai",
    company: "Emirates Flight Catering",
    title: "Production Chef",
    industry: "Catering",
    experience: "5+ yrs",
    salary: "AED 6,000",
    education: "Diploma",
    english: "Good",
    benefits: "Housing",
    matchScore: 97,
  },
  {
    id: "JOB-023",
    country: "Qatar",
    code: "qa",
    city: "Doha",
    company: "Qatar Duty Free",
    title: "Commis I",
    industry: "Hospitality",
    experience: "2+ yrs",
    salary: "QAR 3,200",
    education: "Certificate",
    english: "Basic",
    benefits: "Meals",
    matchScore: 86,
  },
  {
    id: "JOB-024",
    country: "Saudi Arabia",
    code: "sa",
    city: "Riyadh",
    company: "Calo",
    title: "Line Cook",
    industry: "Food Tech",
    experience: "2+ yrs",
    salary: "SAR 4,200",
    education: "Certificate",
    english: "Intermediate",
    benefits: "Medical",
    matchScore: 87,
  },
  {
    id: "JOB-025",
    country: "UAE",
    code: "ae",
    city: "Dubai",
    company: "Jumeirah Hotels",
    title: "Chef de Partie",
    industry: "Luxury Hotel",
    experience: "5+ yrs",
    salary: "AED 6,200",
    education: "Diploma",
    english: "Good",
    benefits: "Housing",
    matchScore: 98,
  },
];
