/**
 * Seeds overseas employment job listings into Neon if the catalog is empty.
 * Run: npx tsx prisma/seed-employment-jobs.ts
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const JOBS = [
  {
    company: "Gulf Build Co.",
    title: "Construction Supervisor",
    country: "United Arab Emirates",
    city: "Dubai",
    salaryMin: 1800,
    salaryMax: 2800,
    salaryCurrency: "USD",
    visaSponsorship: true,
    requirements: ["3+ years site experience", "Safety certification"],
    skills: ["Construction", "Mason"],
    jobType: "FULL_TIME" as const,
    description: "Supervise residential construction crews across Dubai projects.",
    experienceYears: 3,
    educationLevel: "Diploma",
    languages: ["English", "Arabic"],
  },
  {
    company: "Al Noor Hospitals",
    title: "Registered Nurse",
    country: "Saudi Arabia",
    city: "Riyadh",
    salaryMin: 2200,
    salaryMax: 3200,
    salaryCurrency: "USD",
    visaSponsorship: true,
    requirements: ["Nursing license", "2+ years hospital experience"],
    skills: ["Nurse", "Caregiver"],
    jobType: "FULL_TIME" as const,
    description: "Provide inpatient care in a tertiary hospital setting.",
    experienceYears: 2,
    educationLevel: "Bachelor",
    languages: ["English"],
  },
  {
    company: "Sakura Care Group",
    title: "Caregiver",
    country: "Japan",
    city: "Osaka",
    salaryMin: 1600,
    salaryMax: 2300,
    salaryCurrency: "USD",
    visaSponsorship: true,
    requirements: ["Caregiving certificate", "Basic Japanese preferred"],
    skills: ["Caregiver"],
    jobType: "FULL_TIME" as const,
    description: "Support elderly residents in assisted living facilities.",
    experienceYears: 1,
    educationLevel: "Vocational Training",
    languages: ["Japanese", "English"],
  },
  {
    company: "TechBridge Asia",
    title: "Software Engineer",
    country: "Singapore",
    city: "Singapore",
    salaryMin: 4500,
    salaryMax: 7000,
    salaryCurrency: "USD",
    visaSponsorship: true,
    requirements: ["2+ years backend or fullstack", "Degree in CS or related"],
    skills: ["Software Engineer", "IT Support"],
    jobType: "FULL_TIME" as const,
    description: "Build cloud services for regional fintech clients.",
    experienceYears: 2,
    educationLevel: "Bachelor",
    languages: ["English"],
  },
  {
    company: "Horizon Hotels",
    title: "Hotel Front Desk",
    country: "Qatar",
    city: "Doha",
    salaryMin: 1200,
    salaryMax: 1800,
    salaryCurrency: "USD",
    visaSponsorship: true,
    requirements: ["Hospitality experience", "Customer service skills"],
    skills: ["Hotel Staff", "Customer Support"],
    jobType: "FULL_TIME" as const,
    description: "Manage guest check-in and concierge requests.",
    experienceYears: 1,
    educationLevel: "HSC",
    languages: ["English", "Arabic"],
  },
  {
    company: "Deutsche Maschinen",
    title: "Mechanical Technician",
    country: "Germany",
    city: "Stuttgart",
    salaryMin: 2800,
    salaryMax: 3800,
    salaryCurrency: "EUR",
    visaSponsorship: true,
    requirements: ["Trade certificate", "German A2+ preferred"],
    skills: ["Mechanical Engineer", "Welder"],
    jobType: "FULL_TIME" as const,
    description: "Maintain production machinery on automotive lines.",
    experienceYears: 3,
    educationLevel: "Technical Education",
    languages: ["German", "English"],
  },
  {
    company: "Pacific Logistics",
    title: "Warehouse Associate",
    country: "Australia",
    city: "Melbourne",
    salaryMin: 3200,
    salaryMax: 4000,
    salaryCurrency: "AUD",
    visaSponsorship: false,
    requirements: ["Forklift license preferred", "Physical fitness"],
    skills: ["Warehouse", "Factory Worker"],
    jobType: "FULL_TIME" as const,
    description: "Pick, pack, and ship inventory in a high-volume warehouse.",
    experienceYears: 1,
    educationLevel: "SSC",
    languages: ["English"],
  },
  {
    company: "Maple Health Clinics",
    title: "Healthcare Assistant",
    country: "Canada",
    city: "Toronto",
    salaryMin: 2800,
    salaryMax: 3600,
    salaryCurrency: "CAD",
    visaSponsorship: true,
    requirements: ["Caregiving or nursing assistant cert"],
    skills: ["Caregiver", "Nurse"],
    jobType: "FULL_TIME" as const,
    description: "Assist clinical staff with patient care routines.",
    experienceYears: 2,
    educationLevel: "Diploma",
    languages: ["English"],
  },
  {
    company: "Seoul BuildTech",
    title: "Electrician",
    country: "South Korea",
    city: "Seoul",
    salaryMin: 2000,
    salaryMax: 2800,
    salaryCurrency: "USD",
    visaSponsorship: true,
    requirements: ["Electrical trade certificate", "2+ years experience"],
    skills: ["Electrician"],
    jobType: "FULL_TIME" as const,
    description: "Install and maintain electrical systems on commercial sites.",
    experienceYears: 2,
    educationLevel: "Trade Certificates",
    languages: ["Korean", "English"],
  },
  {
    company: "Desert Fleet Services",
    title: "Heavy Vehicle Driver",
    country: "Kuwait",
    city: "Kuwait City",
    salaryMin: 1400,
    salaryMax: 2000,
    salaryCurrency: "USD",
    visaSponsorship: true,
    requirements: ["Valid heavy vehicle license", "Clean driving record"],
    skills: ["Driver"],
    jobType: "FULL_TIME" as const,
    description: "Transport materials across industrial sites.",
    experienceYears: 2,
    educationLevel: "SSC",
    languages: ["English", "Arabic"],
  },
  {
    company: "Kitchen Collective",
    title: "Sous Chef",
    country: "Malaysia",
    city: "Kuala Lumpur",
    salaryMin: 1500,
    salaryMax: 2200,
    salaryCurrency: "USD",
    visaSponsorship: true,
    requirements: ["Culinary diploma or equivalent experience"],
    skills: ["Chef", "Hotel Staff"],
    jobType: "FULL_TIME" as const,
    description: "Lead line cooks in a busy international kitchen.",
    experienceYears: 3,
    educationLevel: "Diploma",
    languages: ["English"],
  },
  {
    company: "BrightPath Tutors",
    title: "English Language Teacher",
    country: "United Arab Emirates",
    city: "Abu Dhabi",
    salaryMin: 2500,
    salaryMax: 3500,
    salaryCurrency: "USD",
    visaSponsorship: true,
    requirements: ["TEFL/TESOL or teaching degree", "IELTS 7.0+"],
    skills: ["Language Teacher"],
    jobType: "FULL_TIME" as const,
    description: "Teach English to adult and school-age learners.",
    experienceYears: 2,
    educationLevel: "Bachelor",
    languages: ["English"],
  },
];

async function main() {
  const count = await prisma.jobListing.count({
    where: { deletedAt: null, status: "ACTIVE" },
  });
  if (count > 0) {
    console.log(`Job catalog already has ${count} listings. Skipping seed.`);
    return;
  }
  await prisma.jobListing.createMany({ data: JOBS });
  console.log(`Seeded ${JOBS.length} job listings into Neon.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
